-- MySQL Script generated by MySQL Workbench
-- Sat Dec 30 17:06:22 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`utilisateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`utilisateur` (
  `uti_id` INT NOT NULL,
  `uti_nom` VARCHAR(45) NULL,
  `uti_prenom` VARCHAR(45) NULL,
  `uti_password` VARCHAR(45) NULL,
  PRIMARY KEY (`uti_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`groupe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`groupe` (
  `grp_id` INT NOT NULL,
  `grp_nom` VARCHAR(45) NULL,
  PRIMARY KEY (`grp_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`fil de discussion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`fil de discussion` (
  `fil_id` INT NOT NULL,
  `fil_nom` VARCHAR(45) NULL,
  `fil_groupe_id` INT NOT NULL,
  `fil_premier_msg_id` INT NULL,
  `fil_date_dernier_msg` DATETIME NULL,
  PRIMARY KEY (`fil_id`, `fil_groupe_id`),
  INDEX `fk_fil de discussion_groupe1_idx` (`fil_groupe_id` ASC),
  INDEX `fk_fil de discussion_message_idx` (`fil_premier_msg_id` ASC),
  CONSTRAINT `fk_fil de discussion_groupe1`
    FOREIGN KEY (`fil_groupe_id`)
    REFERENCES `mydb`.`groupe` (`grp_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`message` (
  `msg_id` INT NOT NULL,
  `msg_date` DATETIME NULL,
  `msg_contenu` VARCHAR(512) NULL,
  `msg_fil_id` INT NOT NULL,
  `msg_groupe_id` INT NOT NULL,
  PRIMARY KEY (`msg_id`, `msg_fil_id`, `msg_groupe_id`),
  INDEX `fk_message_fil de discussion2_idx` (`msg_fil_id` ASC, `msg_groupe_id` ASC),
  CONSTRAINT `fk_message_fil de discussion2`
    FOREIGN KEY (`msg_fil_id` , `msg_groupe_id`)
    REFERENCES `mydb`.`fil de discussion` (`fil_id` , `fil_groupe_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`utilisateur_has_groupe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`utilisateur_has_groupe` (
  `utilisateur_uti_id` INT NOT NULL,
  `groupe_grp_id` INT NOT NULL,
  PRIMARY KEY (`utilisateur_uti_id`, `groupe_grp_id`),
  INDEX `fk_utilisateur_has_groupe_groupe1_idx` (`groupe_grp_id` ASC),
  INDEX `fk_utilisateur_has_groupe_utilisateur_idx` (`utilisateur_uti_id` ASC),
  CONSTRAINT `fk_utilisateur_has_groupe_utilisateur`
    FOREIGN KEY (`utilisateur_uti_id`)
    REFERENCES `mydb`.`utilisateur` (`uti_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_utilisateur_has_groupe_groupe1`
    FOREIGN KEY (`groupe_grp_id`)
    REFERENCES `mydb`.`groupe` (`grp_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
