/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client;

import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import network.ClientNet;
import struct.Groupe;

/**
 *
 * @author Mael "ADDRMeridan" Moulin
 */
public class ClientUI_NewTicket extends javax.swing.JFrame {

	/**
	 * DEFAULT
	 */
	private static final long serialVersionUID = 1L;
	ClientNet net;
	String username;
	List<Groupe> grps;

	/**
	 * Creates new form ClientUI_NewTicket
	 * 
	 * @param net
	 * @param username
	 */
	public ClientUI_NewTicket(ClientNet net, String username) {
		try {
			this.net = net;
			this.username = username;
			this.grps = getGrps();
		} catch (IOException | ClassNotFoundException ex) {
			Logger.getLogger(ClientUI_NewTicket.class.getName()).log(Level.SEVERE, null, ex);
		}
		initComponents();
	}

	private List<Groupe> getGrps() throws IOException, ClassNotFoundException {

		return net.askGroupList(username);
	}

	private DefaultListModel<String> getGrpsNames() {

		DefaultListModel<String> tmp = new DefaultListModel<>();
		if (grps != null) {
			grps.forEach((g) -> {
				tmp.addElement(g.getNom());
			});
		}
		return tmp;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		titleBox = new javax.swing.JTextField();
		jLabel1 = new javax.swing.JLabel();
		jSeparator1 = new javax.swing.JSeparator();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		Tree = new javax.swing.JList<>();
		jScrollPane2 = new javax.swing.JScrollPane();
		messBox = new javax.swing.JTextArea();
		jButton1 = new javax.swing.JButton();
		returnButton = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setPreferredSize(new java.awt.Dimension(800, 600));

		titleBox.setText("Title");
		titleBox.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				titleBoxActionPerformed(evt);
			}
		});

		jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
		jLabel1.setText("Title:");

		jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
		jLabel2.setText("Select Group:");

		jLabel3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
		jLabel3.setText("Message:");

		Tree.setModel(getGrpsNames());
		Tree.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
		jScrollPane1.setViewportView(Tree);

		messBox.setColumns(20);
		messBox.setRows(5);
		jScrollPane2.setViewportView(messBox);

		jButton1.setText("Send Ticket");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		returnButton.setText("Return");
		returnButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				returnButtonActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
								.addGroup(layout.createSequentialGroup().addComponent(jLabel1)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(titleBox))
								.addGroup(layout
										.createSequentialGroup().addComponent(jLabel2).addGap(18, 18, 18)
										.addComponent(jLabel3).addGap(0, 0, Short.MAX_VALUE))
								.addGroup(layout.createSequentialGroup()
										.addGroup(layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
												.addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 182,
														Short.MAX_VALUE)
												.addComponent(returnButton, javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
										.addGap(18, 18, 18)
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 548,
														Short.MAX_VALUE))))
						.addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(titleBox))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel2).addComponent(jLabel3))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(
								layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
										.addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 230,
												Short.MAX_VALUE)
										.addComponent(jScrollPane2))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
								.addComponent(returnButton, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void titleBoxActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_titleBoxActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_titleBoxActionPerformed

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed

		String grpName = (String) Tree.getSelectedValue();
		int grpId = -1;
		boolean found = false;
		int i = 0;
		while (i < grps.size() && !found) {
			if (grps.get(i).getNom() == null ? grpName == null : grps.get(i).getNom().equals(grpName)) {
				found = true;
				grpId = grps.get(i).getIdGroupe();
			}
		}
		try {
			net.createTicket(titleBox.getText(), grpId, messBox.getText());
		} catch (IOException ex) {
			Logger.getLogger(ClientUI_NewTicket.class.getName()).log(Level.SEVERE, null, ex);
		}
		new ClientUI_Tree(net, username).setVisible(true);
		this.setVisible(false);
	}// GEN-LAST:event_jButton1ActionPerformed

	private void returnButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_returnButtonActionPerformed
		new ClientUI_Tree(net, username).setVisible(true);
		this.setVisible(false);
	}// GEN-LAST:event_returnButtonActionPerformed

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JList<String> Tree;
	private javax.swing.JButton jButton1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JSeparator jSeparator1;
	private javax.swing.JTextArea messBox;
	private javax.swing.JButton returnButton;
	private javax.swing.JTextField titleBox;
	// End of variables declaration//GEN-END:variables
}
