/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JTree;
import javax.swing.tree.DefaultMutableTreeNode;
import network.ClientNet;



/**
 *
 * @author blaise
 */
public class InterfaceUtilisateur extends javax.swing.JFrame {

    ClientNet network;
    
    /**
     * Creates new form InterfaceUtilisateur
     */
    public InterfaceUtilisateur(ClientNet network) {
        initComponents();
        this.network = network;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userPanel = new javax.swing.JPanel();
        usernameLabel = new javax.swing.JLabel();
        deconnexionButton = new javax.swing.JButton();
        listeTicketsPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ticketsScrollPanel = new javax.swing.JScrollPane();
        DefaultMutableTreeNode listeGroupes;
        DefaultMutableTreeNode groupe;
        DefaultMutableTreeNode ticket;

        listeGroupes = new DefaultMutableTreeNode("ListeGroupes");

        groupe = new DefaultMutableTreeNode("Groupe1");
        ticket = new DefaultMutableTreeNode("Ticket1");
        groupe.add(ticket);
        ticket = new DefaultMutableTreeNode("Ticket2");
        groupe.add(ticket);
        listeGroupes.add(groupe);

        groupe = new DefaultMutableTreeNode("Groupe2");
        ticket = new DefaultMutableTreeNode("Ticket1");
        groupe.add(ticket);
        ticket = new DefaultMutableTreeNode("Ticket2");
        groupe.add(ticket);
        listeGroupes.add(groupe);
        ticketsArborescence = new JTree(listeGroupes);
        objetPanel = new javax.swing.JPanel();
        objetLabel = new javax.swing.JLabel();
        objetContentLabel = new javax.swing.JLabel();
        discussionScrollPanel = new javax.swing.JScrollPane();
        reponsePanel = new javax.swing.JPanel();
        texteScrollPanel = new javax.swing.JScrollPane();
        reponseTextArea = new javax.swing.JTextArea();
        envoyerButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        usernameLabel.setText("Connecté en tant que " + network.getUsername());

        deconnexionButton.setText("Déconnexion");
        deconnexionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deconnexionButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout userPanelLayout = new javax.swing.GroupLayout(userPanel);
        userPanel.setLayout(userPanelLayout);
        userPanelLayout.setHorizontalGroup(
            userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(usernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deconnexionButton)
                .addContainerGap())
        );
        userPanelLayout.setVerticalGroup(
            userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameLabel)
                    .addComponent(deconnexionButton))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jLabel1.setText("LISTE DES TICKETS");

        javax.swing.GroupLayout listeTicketsPanelLayout = new javax.swing.GroupLayout(listeTicketsPanel);
        listeTicketsPanel.setLayout(listeTicketsPanelLayout);
        listeTicketsPanelLayout.setHorizontalGroup(
            listeTicketsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listeTicketsPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        listeTicketsPanelLayout.setVerticalGroup(
            listeTicketsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listeTicketsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ticketsScrollPanel.setViewportView(ticketsArborescence);

        objetLabel.setText("Objet :");

        objetContentLabel.setText(" ");

        javax.swing.GroupLayout objetPanelLayout = new javax.swing.GroupLayout(objetPanel);
        objetPanel.setLayout(objetPanelLayout);
        objetPanelLayout.setHorizontalGroup(
            objetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(objetPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(objetLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(objetContentLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        objetPanelLayout.setVerticalGroup(
            objetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, objetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(objetLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addComponent(objetContentLabel))
        );

        reponseTextArea.setColumns(20);
        reponseTextArea.setRows(5);
        reponseTextArea.setText("Votre réponse...");
        texteScrollPanel.setViewportView(reponseTextArea);

        envoyerButton.setText("Envoyer");
        envoyerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                envoyerButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout reponsePanelLayout = new javax.swing.GroupLayout(reponsePanel);
        reponsePanel.setLayout(reponsePanelLayout);
        reponsePanelLayout.setHorizontalGroup(
            reponsePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reponsePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(reponsePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(texteScrollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, reponsePanelLayout.createSequentialGroup()
                        .addGap(0, 0, 0)
                        .addComponent(envoyerButton)))
                .addContainerGap())
        );
        reponsePanelLayout.setVerticalGroup(
            reponsePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reponsePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(texteScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(envoyerButton)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ticketsScrollPanel)
                            .addComponent(listeTicketsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(objetPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(reponsePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(discussionScrollPanel))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(userPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(listeTicketsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ticketsScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(objetPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(discussionScrollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(reponsePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 122, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deconnexionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deconnexionButtonActionPerformed
        try {
            network.disconnect();
        } catch (IOException ex) {
            Logger.getLogger(InterfaceUtilisateur.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(false);
        javax.swing.JFrame newframe;
        newframe = new LoginClient();
        newframe.setExtendedState(JFrame.MAXIMIZED_BOTH);
        newframe.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_deconnexionButtonActionPerformed

    private void envoyerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_envoyerButtonActionPerformed
        try {
            network.answerTicket(1, reponseTextArea.getText());
        } catch (IOException ex) {
            Logger.getLogger(InterfaceUtilisateur.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_envoyerButtonActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deconnexionButton;
    private javax.swing.JScrollPane discussionScrollPanel;
    private javax.swing.JButton envoyerButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel listeTicketsPanel;
    private javax.swing.JLabel objetContentLabel;
    private javax.swing.JLabel objetLabel;
    private javax.swing.JPanel objetPanel;
    private javax.swing.JPanel reponsePanel;
    private javax.swing.JTextArea reponseTextArea;
    private javax.swing.JScrollPane texteScrollPanel;
    private javax.swing.JTree ticketsArborescence;
    private javax.swing.JScrollPane ticketsScrollPanel;
    private javax.swing.JPanel userPanel;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables
}
